default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gradejoyV2_development

test:
  <<: *default
  database: gradejoyV2_test

production:
  <<: *default
  database: gradejoyV2_production
